{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.manager.privacy",
    "module": "privacyAnnotation",
    "version": "1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyAnnotation-1.9.jar",
          "url": "privacyAnnotation-1.9.jar",
          "size": 5066,
          "sha512": "e7541d4b76186ba062c4ed353c3bed62bd073b83871c7eefb69342fd98ad735943d91037a3e08f6bbafd3082673933c4a2457d1554496ce73ccbd120c2944732",
          "sha256": "292b1fd26ff1c8403eb31bb4a8f3ce055d200d8a0c508ac477190479850285e5",
          "sha1": "f2a97a91d16102dcdbf9c7de0927240f21ec17d5",
          "md5": "f68c05c1203be53858584b3e051b04f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyAnnotation-1.9.jar",
          "url": "privacyAnnotation-1.9.jar",
          "size": 5066,
          "sha512": "e7541d4b76186ba062c4ed353c3bed62bd073b83871c7eefb69342fd98ad735943d91037a3e08f6bbafd3082673933c4a2457d1554496ce73ccbd120c2944732",
          "sha256": "292b1fd26ff1c8403eb31bb4a8f3ce055d200d8a0c508ac477190479850285e5",
          "sha1": "f2a97a91d16102dcdbf9c7de0927240f21ec17d5",
          "md5": "f68c05c1203be53858584b3e051b04f5"
        }
      ]
    }
  ]
}
