{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.gradle.plugin.privacy",
    "module": "privacyPlugin",
    "version": "1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyPlugin-1.9.jar",
          "url": "privacyPlugin-1.9.jar",
          "size": 46608,
          "sha512": "06731beecfbc65438d3e1c71c7cfc40f71adb1372db82fb14168894913acec7d10e50efe4f14d1d8925267a7ba4a34b042fc1ec65fbb4c57f0f968c6211314f9",
          "sha256": "3b1442502c393f580f88da55a7f98d693e5ba67182d7fa2cf8c9caf5ba8dcccd",
          "sha1": "87aaa6ce856a8d504ca4890396bbd1086e157ca3",
          "md5": "e95540a2446ad7d7890c4bf0fbdbdd1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.eric.manager.privacy",
          "module": "privacyAnnotation",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyPlugin-1.9.jar",
          "url": "privacyPlugin-1.9.jar",
          "size": 46608,
          "sha512": "06731beecfbc65438d3e1c71c7cfc40f71adb1372db82fb14168894913acec7d10e50efe4f14d1d8925267a7ba4a34b042fc1ec65fbb4c57f0f968c6211314f9",
          "sha256": "3b1442502c393f580f88da55a7f98d693e5ba67182d7fa2cf8c9caf5ba8dcccd",
          "sha1": "87aaa6ce856a8d504ca4890396bbd1086e157ca3",
          "md5": "e95540a2446ad7d7890c4bf0fbdbdd1b"
        }
      ]
    }
  ]
}
