{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.manager.privacy",
    "module": "privacyProxcy",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyProxcy-2.1.aar",
          "url": "privacyProxcy-2.1.aar",
          "size": 23860,
          "sha512": "58394a335dacd55ff0f8d3358ffe438e44b2e34e7c7ac2c4a4ae1e58dd969cd16400be59959eebb0f83d7fce84c48acd0951de8b2d6d2408ce5ddbdfc2b37980",
          "sha256": "c459dac1a619b72bc6b71bceb331bfd5e1060baed36b8bd7eaf2eadc6219bfb3",
          "sha1": "fd513997de829dedfcf6456fbc49a32b2dd38e2c",
          "md5": "24bca3810dd973eb6620081503c6bb3d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.14"
          }
        },
        {
          "group": "com.eric.manager.privacy",
          "module": "privacyAnnotation",
          "version": {
            "requires": "2.1"
          }
        }
      ],
      "files": [
        {
          "name": "privacyProxcy-2.1.aar",
          "url": "privacyProxcy-2.1.aar",
          "size": 23860,
          "sha512": "58394a335dacd55ff0f8d3358ffe438e44b2e34e7c7ac2c4a4ae1e58dd969cd16400be59959eebb0f83d7fce84c48acd0951de8b2d6d2408ce5ddbdfc2b37980",
          "sha256": "c459dac1a619b72bc6b71bceb331bfd5e1060baed36b8bd7eaf2eadc6219bfb3",
          "sha1": "fd513997de829dedfcf6456fbc49a32b2dd38e2c",
          "md5": "24bca3810dd973eb6620081503c6bb3d"
        }
      ]
    }
  ]
}
