{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.manager.privacy",
    "module": "privacyProxcy",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyProxcy-1.8.aar",
          "url": "privacyProxcy-1.8.aar",
          "size": 20737,
          "sha512": "91243aac11aad2a60c1947ea593fadc5514fc5b9e31046611ad8a5778e08ae1c6f9a6fda60cf00662af4fa7eaf7112abf0c7c814f49cf4bde86544860d5f1a74",
          "sha256": "b290bc3584b647efcdfac10a8cc58f598d502303033921acda12fb9e11561cd2",
          "sha1": "2ee6c05136391987dd730a587995f18e791634ac",
          "md5": "cbb2f822962d2da2f1b1e1fcf59c96f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.14"
          }
        },
        {
          "group": "com.eric.manager.privacy",
          "module": "privacyAnnotation",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "privacyProxcy-1.8.aar",
          "url": "privacyProxcy-1.8.aar",
          "size": 20737,
          "sha512": "91243aac11aad2a60c1947ea593fadc5514fc5b9e31046611ad8a5778e08ae1c6f9a6fda60cf00662af4fa7eaf7112abf0c7c814f49cf4bde86544860d5f1a74",
          "sha256": "b290bc3584b647efcdfac10a8cc58f598d502303033921acda12fb9e11561cd2",
          "sha1": "2ee6c05136391987dd730a587995f18e791634ac",
          "md5": "cbb2f822962d2da2f1b1e1fcf59c96f4"
        }
      ]
    }
  ]
}
