{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.manager.privacy",
    "module": "privacyAnnotation",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyAnnotation-2.1.jar",
          "url": "privacyAnnotation-2.1.jar",
          "size": 5066,
          "sha512": "5962c27ddbc05eef16d8e297f9682075e3fbcaa2a096307d968c1bcf0f9585d79b5054189f892ac3967797d6db16b858a8ccdae245c4224c646794b2956c8dbf",
          "sha256": "2ada95c70ad85839875b4d2aa4b68ff1475c0245864595c3efa807df7595ff56",
          "sha1": "824272233aadfc545adadc19258d78fb454f01f7",
          "md5": "6fb782fd2f9de281079543d8107e5d39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyAnnotation-2.1.jar",
          "url": "privacyAnnotation-2.1.jar",
          "size": 5066,
          "sha512": "5962c27ddbc05eef16d8e297f9682075e3fbcaa2a096307d968c1bcf0f9585d79b5054189f892ac3967797d6db16b858a8ccdae245c4224c646794b2956c8dbf",
          "sha256": "2ada95c70ad85839875b4d2aa4b68ff1475c0245864595c3efa807df7595ff56",
          "sha1": "824272233aadfc545adadc19258d78fb454f01f7",
          "md5": "6fb782fd2f9de281079543d8107e5d39"
        }
      ]
    }
  ]
}
