{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.manager.privacy",
    "module": "privacyAnnotation",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyAnnotation-1.0.jar",
          "url": "privacyAnnotation-1.0.jar",
          "size": 5066,
          "sha512": "0ded3b2e524529a26d22b618d4c2e8959f533efa1ae0591396c4d9d30ac91abfc83347127d239ae3f15f9c03af6376d8a2d8184d0db17189d7de9031b3b35720",
          "sha256": "9391e3f99bbbcec44ae06f533a94fd4f265c39dd01d27f701b7ae48683537fbf",
          "sha1": "10d01e6fb409ed3779305c6390151ae708960f03",
          "md5": "5181ae276557758f970fb67ca3a01f14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyAnnotation-1.0.jar",
          "url": "privacyAnnotation-1.0.jar",
          "size": 5066,
          "sha512": "0ded3b2e524529a26d22b618d4c2e8959f533efa1ae0591396c4d9d30ac91abfc83347127d239ae3f15f9c03af6376d8a2d8184d0db17189d7de9031b3b35720",
          "sha256": "9391e3f99bbbcec44ae06f533a94fd4f265c39dd01d27f701b7ae48683537fbf",
          "sha1": "10d01e6fb409ed3779305c6390151ae708960f03",
          "md5": "5181ae276557758f970fb67ca3a01f14"
        }
      ]
    }
  ]
}
