{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.manager.privacy",
    "module": "privacyAnnotation",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyAnnotation-1.0.jar",
          "url": "privacyAnnotation-1.0.jar",
          "size": 4267,
          "sha512": "941fa6d85b58219d9db6680b243dafb26c51bf6bab388d49b0932a8dac20b41f5f4a88d9c0301bfd1f139ea7b180a97e565464a3958cc7740dc4274da874c9fb",
          "sha256": "85daa2aa18e034a485fd5d50f2a4a4227929e2ddf462f695870be0368e9611d4",
          "sha1": "0821a8bada6bf2a1f1bd35fb2aca81b52bbf0d70",
          "md5": "8a5d5765795a0e4701ec886895fc10c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyAnnotation-1.0.jar",
          "url": "privacyAnnotation-1.0.jar",
          "size": 4267,
          "sha512": "941fa6d85b58219d9db6680b243dafb26c51bf6bab388d49b0932a8dac20b41f5f4a88d9c0301bfd1f139ea7b180a97e565464a3958cc7740dc4274da874c9fb",
          "sha256": "85daa2aa18e034a485fd5d50f2a4a4227929e2ddf462f695870be0368e9611d4",
          "sha1": "0821a8bada6bf2a1f1bd35fb2aca81b52bbf0d70",
          "md5": "8a5d5765795a0e4701ec886895fc10c7"
        }
      ]
    }
  ]
}
