{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.gradle.plugin.privacy",
    "module": "privacyPlugin",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyPlugin-2.0.jar",
          "url": "privacyPlugin-2.0.jar",
          "size": 46519,
          "sha512": "232b394682554f8d1fdc1a514aba00f080ca9a1702c83c6fcd8643bd9461f06f829bda45f12efd6f78fe549691810364cdb85de792e2e4b94495e2f5bffe046c",
          "sha256": "4a32fc3a76c992e56b313d808c1508b8aa1bb2e690a680c2286cf0b2de6cd58d",
          "sha1": "8c43cfb340aa56d2437552b4fcdc34ef18f44e60",
          "md5": "0e2f984155582bcc91157f932abf352f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.eric.manager.privacy",
          "module": "privacyAnnotation",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyPlugin-2.0.jar",
          "url": "privacyPlugin-2.0.jar",
          "size": 46519,
          "sha512": "232b394682554f8d1fdc1a514aba00f080ca9a1702c83c6fcd8643bd9461f06f829bda45f12efd6f78fe549691810364cdb85de792e2e4b94495e2f5bffe046c",
          "sha256": "4a32fc3a76c992e56b313d808c1508b8aa1bb2e690a680c2286cf0b2de6cd58d",
          "sha1": "8c43cfb340aa56d2437552b4fcdc34ef18f44e60",
          "md5": "0e2f984155582bcc91157f932abf352f"
        }
      ]
    }
  ]
}
