{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.gradle.plugin.privacy",
    "module": "privacyPlugin",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyPlugin-2.0.jar",
          "url": "privacyPlugin-2.0.jar",
          "size": 46494,
          "sha512": "2871633d120f3194ecb80ca7d5aa4020e321e3bf7c62391d8b9702154bbeb5aed8c654a1b322c06c5b9d4ef85e5496fa76c140472ff00ed248c5548ad340eb5c",
          "sha256": "3e1a052f7ac0dba4db25e83b201a25ff4f8c7990684280b26ca9169e0ba2031f",
          "sha1": "4f9040507200702d3468ab6d16235b5ddf05b8f2",
          "md5": "da0cb4ebe2ceb8e47a0d6a0e84bd872c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.eric.manager.privacy",
          "module": "privacyAnnotation",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyPlugin-2.0.jar",
          "url": "privacyPlugin-2.0.jar",
          "size": 46494,
          "sha512": "2871633d120f3194ecb80ca7d5aa4020e321e3bf7c62391d8b9702154bbeb5aed8c654a1b322c06c5b9d4ef85e5496fa76c140472ff00ed248c5548ad340eb5c",
          "sha256": "3e1a052f7ac0dba4db25e83b201a25ff4f8c7990684280b26ca9169e0ba2031f",
          "sha1": "4f9040507200702d3468ab6d16235b5ddf05b8f2",
          "md5": "da0cb4ebe2ceb8e47a0d6a0e84bd872c"
        }
      ]
    }
  ]
}
