{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.manager.privacy",
    "module": "privacyProxcy",
    "version": "1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyProxcy-1.9.aar",
          "url": "privacyProxcy-1.9.aar",
          "size": 20892,
          "sha512": "620a7a187d0def409d84ba2dd1f386ac0a14d01263b8f562342cf0b1a570838978f73c3949a9b28b7056a7aaa2c1abbf8786c887886d3c31d31aaee07a28744b",
          "sha256": "30ee183fbee3ea4e5a62faee426c5d9fb6e7d62c70e727daadd8fbb0ac15f170",
          "sha1": "a0eaab81aa57770f0b59399490c8ece6d450e24a",
          "md5": "2d8c4b9750107c961469ec0b7a79ba3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.14"
          }
        },
        {
          "group": "com.eric.manager.privacy",
          "module": "privacyAnnotation",
          "version": {
            "requires": "1.9"
          }
        }
      ],
      "files": [
        {
          "name": "privacyProxcy-1.9.aar",
          "url": "privacyProxcy-1.9.aar",
          "size": 20892,
          "sha512": "620a7a187d0def409d84ba2dd1f386ac0a14d01263b8f562342cf0b1a570838978f73c3949a9b28b7056a7aaa2c1abbf8786c887886d3c31d31aaee07a28744b",
          "sha256": "30ee183fbee3ea4e5a62faee426c5d9fb6e7d62c70e727daadd8fbb0ac15f170",
          "sha1": "a0eaab81aa57770f0b59399490c8ece6d450e24a",
          "md5": "2d8c4b9750107c961469ec0b7a79ba3b"
        }
      ]
    }
  ]
}
