{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.gradle.plugin.privacy",
    "module": "privacyPlugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyPlugin-1.0.jar",
          "url": "privacyPlugin-1.0.jar",
          "size": 45611,
          "sha512": "f08348068a223377812f4ae0f87e59edfdc7c38bdf49165a929aaafb7d306dd15e878c582e713af39794240bac8d9110ace18a0b8ccb1c3901252b22a0db48e9",
          "sha256": "4547967c8e5ef8ad258a8cb17971a2f361510c7baa97b97c11e2cd09708d8028",
          "sha1": "1356ea586380055493f3a22ef5eacd3f5978da90",
          "md5": "aaa343c4b7495b78e9abec74c742523a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.eric.manager.privacy",
          "module": "privacyAnnotation",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyPlugin-1.0.jar",
          "url": "privacyPlugin-1.0.jar",
          "size": 45611,
          "sha512": "f08348068a223377812f4ae0f87e59edfdc7c38bdf49165a929aaafb7d306dd15e878c582e713af39794240bac8d9110ace18a0b8ccb1c3901252b22a0db48e9",
          "sha256": "4547967c8e5ef8ad258a8cb17971a2f361510c7baa97b97c11e2cd09708d8028",
          "sha1": "1356ea586380055493f3a22ef5eacd3f5978da90",
          "md5": "aaa343c4b7495b78e9abec74c742523a"
        }
      ]
    }
  ]
}
