{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eric.gradle.plugin.privacy",
    "module": "privacyPlugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyPlugin-1.0.jar",
          "url": "privacyPlugin-1.0.jar",
          "size": 45410,
          "sha512": "3bf033863ea4289c233d10a4e8fa611697821f2b4e9ff44190a342908b543f99edf8252e92bbb3ab539d95ae30c54e4fcca9370b2f804fc97768b8a8e6dd6b1f",
          "sha256": "3c5476bf3bbf29fb18e4690d19db8dbb9a8d72af25c0029274ff42d22a55530e",
          "sha1": "4d9c68cbc9d2a7615dd18e3c73c16548a8a4b31a",
          "md5": "32716b44dcee17934f7a7e8e6bd34ea6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.eric.manager.privacy",
          "module": "privacyAnnotation",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "privacyPlugin-1.0.jar",
          "url": "privacyPlugin-1.0.jar",
          "size": 45410,
          "sha512": "3bf033863ea4289c233d10a4e8fa611697821f2b4e9ff44190a342908b543f99edf8252e92bbb3ab539d95ae30c54e4fcca9370b2f804fc97768b8a8e6dd6b1f",
          "sha256": "3c5476bf3bbf29fb18e4690d19db8dbb9a8d72af25c0029274ff42d22a55530e",
          "sha1": "4d9c68cbc9d2a7615dd18e3c73c16548a8a4b31a",
          "md5": "32716b44dcee17934f7a7e8e6bd34ea6"
        }
      ]
    }
  ]
}
